name: linux-benchmark
on:
  workflow_call:
    secrets:
      TRITONBENCH_SCRIBE_GRAPHQL_ACCESS_TOKEN:
        required: True
        description: |
          Tritonbench Scribe Graph Access Token
    inputs:
      runner:
        required: True
        type: string
        description: |
          Runner to use for the benchmark
      runner_full_name:
        required: True
        type: string
        description: |
          Full runner label to use for runs-on
      test_type:
        required: True
        type: string
        description: |
          Type of the test (single or abtest)
      benchmark_name:
        required: True
        type: string
        description: |
          Benchmark name
      venv_name:
        required: True
        default: "triton-main"
        type: string
        description: |
          Name of the virtual environment to use for the benchmark
      side_a_triton:
        type: string
        required: False
        default: "triton-lang/triton"
        description: |
          Triton repository to test on side A, e.g., "triton-lang/triton"
      side_a_commit:
        type: string
        required: False
        description: |
          Triton commit or tag to test on side A, e.g., "main"
      side_b_triton:
        type: string
        required: False
        default: "triton-lang/triton"
        description: |
          Triton repository to test on side B, e.g., "triton-lang/triton"
      side_b_commit:
        type: string
        required: False
        description: |
          Triton commit or tag to test on side B, e.g., "main"

jobs:
  linux-benchmark:
    if: github.repository_owner == 'meta-pytorch'
    runs-on: ${{ inputs.runner_full_name }}
    timeout-minutes: 240
    environment: docker-s3-upload
    permissions:
      id-token: write
      contents: read
    env:
      WORKSPACE_DIR: "/workspace"
      UV_VENV_DIR: "/workspace/uv_venvs"
      SETUP_SCRIPT: "/workspace/setup_instance.sh"
      RUNNER_TYPE: ${{ inputs.runner_full_name }}
      JOB_NAME: tritonbench-${{ inputs.runner }}-benchmark-${{ inputs.venv_name }}-${{ inputs.test_type }}-${{ inputs.benchmark_name }}
      TRITONBENCH_SIDE_A_ENV: ${{ inputs.test_type == 'abtest' && 'triton-side-a' || inputs.venv_name }}
      CONDA_ENV: ${{ inputs.test_type == 'abtest' && 'triton-side-a' || inputs.venv_name }}
      TRITONBENCH_SIDE_B_ENV: "triton-side-b"
      TRITONBENCH_SCRIBE_GRAPHQL_ACCESS_TOKEN: ${{ secrets.TRITONBENCH_SCRIBE_GRAPHQL_ACCESS_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout Tritonbench
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Tune Nvidia GPU
        if: ${{ inputs.runner == 'h100' }}
        run: |
          bash .ci/gpu/tune-gcp-h100.sh
          sudo ldconfig
          nvidia-smi

      - name: Authenticate with AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::308535385114:role/gha_workflow_upload-benchmark-results
          role-duration-seconds: 18000
          aws-region: us-east-1

      - name: Setup pytorch and tritonbench environment
        run: |
          set -eux
          if [ "${{ inputs.runner }}" = "h100" ]; then
            bash ./.ci/tritonbench/setup-nvidia-path.sh
            bash ./.ci/tritonbench/install.sh --refresh-pytorch
          elif [ "${{ inputs.runner }}" = "mi350" ]; then
            bash ./.ci/tritonbench/setup-env.sh --hip --no-build --triton-main --meta-triton
          else
            echo "Unknown runner: ${{ inputs.runner }}"
            exit 1
          fi

      - name: Setup uploader dependencies
        run: |
          set -eux
          . "${SETUP_SCRIPT}"
          uv pip install -r .ci/upload/requirements.txt

      - name: Compile Triton (Side A)
        run: |
          set -eux
          if [ "${{ inputs.test_type }}" = "periodic" ]; then
            if [ "${{ inputs.venv_name }}" = "triton-main" ]; then
              bash ./.ci/triton/install-triton-main.sh --no-clone
            elif [ "${{ inputs.venv_name }}" = "meta-triton" ]; then
              bash ./.ci/triton/install-meta-triton.sh --no-clone
            else
              echo "Unknown venv name: ${{ inputs.venv_name }}"
              exit 1
            fi
            echo "TRITONBENCH_SIDE_A_ENV=${TRITONBENCH_SIDE_A_ENV}" >> "${GITHUB_ENV}"
          else
            echo "single or abtest, alreadys recompile triton"
            bash ./.ci/triton/install.sh --repo ${{ inputs.side_a_triton }} --commit ${{ inputs.side_a_commit }} --side a
            echo "TRITONBENCH_SIDE_A_ENV=triton-side-a" >> "${GITHUB_ENV}"
          fi
          cat "${SETUP_SCRIPT}"

      - name: Benchmark Triton (Side A)
        run: |
          set -eux
          bash .ci/tritonbench/run-benchmark.sh ${{ inputs.benchmark_name }} --conda-env "${TRITONBENCH_SIDE_A_ENV}"
          mkdir -p benchmark-output
          cp -r ".benchmarks/${{ inputs.benchmark_name }}" "benchmark-output/${TRITONBENCH_SIDE_A_ENV}"
          sudo rm -rf .benchmarks || true

      - name: Compile Triton side B
        if: ${{ inputs.test_type == 'abtest' && inputs.side_b_triton && inputs.side_b_commit }}
        run: |
          set -eux
          bash ./.ci/triton/install.sh --repo ${{ inputs.side_b_triton }} --commit ${{ inputs.side_b_commit }} --side b
          echo 'TRITONBENCH_SIDE_B_ENV=triton-side-b' >> "${GITHUB_ENV}"

      - name: Benchmark Triton (Side B)
        if: ${{ inputs.test_type == 'abtest' && inputs.side_b_triton && inputs.side_b_commit }}
        run: |
          set -eux
          bash .ci/tritonbench/run-benchmark.sh ${{ inputs.benchmark_name }} --conda-env "${TRITONBENCH_SIDE_B_ENV}"
          mkdir -p benchmark-output
          cp -r ".benchmarks/${{ inputs.benchmark_name }}" "benchmark-output/${TRITONBENCH_SIDE_B_ENV}"
          sudo rm -rf .benchmarks || true

      - name: Upload result to GH Actions Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.JOB_NAME }}
          path: benchmark-output/

      - name: Upload result to Scribe
        run: |
          set -xeu
          . "${SETUP_SCRIPT}"
          if [[ -n "${TRITONBENCH_SIDE_A_ENV}" ]]; then
            side_a_json=$(find "./benchmark-output/${TRITONBENCH_SIDE_A_ENV}" -name "result.json" | sort -r | head -n 1)
            python3 ./.ci/upload/scribe.py --json "${side_a_json}"
          fi
          if [[ -n "${TRITONBENCH_SIDE_B_ENV}" ]] && [[ -e "./benchmark-output/${TRITONBENCH_SIDE_B_ENV}" ]]; then
            side_b_json=$(find "./benchmark-output/${TRITONBENCH_SIDE_B_ENV}" -name "result.json" | sort -r | head -n 1)
            python3 ./.ci/upload/scribe.py --json "${side_b_json}"
          fi

      - name: Rewrite Tritonbench json to ClickHouse style
        run: |
          set -xeu
          . "${SETUP_SCRIPT}"
          if [[ -n "${TRITONBENCH_SIDE_A_ENV}" ]]; then
            side_a_json=$(find "./benchmark-output/${TRITONBENCH_SIDE_A_ENV}" -name "result.json" | sort -r | head -n 1)
            python3 ./.ci/test_infra/oss_ci_benchmark_v3.py --json "${side_a_json}" \
              --output "benchmark-output/clickhouse-results/result-${TRITONBENCH_SIDE_A_ENV}.json"
          fi
          if [[ -n "${TRITONBENCH_SIDE_B_ENV}" ]] && [[ -e "./benchmark-output/${TRITONBENCH_SIDE_B_ENV}" ]]; then
            side_b_json=$(find "./benchmark-output/${TRITONBENCH_SIDE_B_ENV}" -name "result.json" | sort -r | head -n 1)
            python3 ./.ci/test_infra/oss_ci_benchmark_v3.py --json "${side_b_json}" \
              --output "benchmark-output/clickhouse-results/result-${TRITONBENCH_SIDE_B_ENV}.json"
          fi

      - name: Upload result to ClickHouse
        uses: pytorch/test-infra/.github/actions/upload-benchmark-results@main
        with:
          benchmark-results-dir: benchmark-output/clickhouse-results
          dry-run: false
          schema-version: v3
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Restore Nvidia GPU
        if: ${{ always() && inputs.runner == 'h100' }}
        run: |
          bash .ci/gpu/reset-gcp-h100.sh
          sudo ldconfig
          nvidia-smi
