name: TritonBench Timing Accuracy Benchmark
permissions:
  contents: read
  id-token: write
on:
  workflow_dispatch:


jobs:
  h100-meta-triton-timing-accuracy-benchmark:
    uses: ./.github/workflows/_linux-benchmark-h100.yml
    with:
      test_type:  'periodic'
      venv_name: "meta-triton"
      benchmark_name: "timing_accuracy"
    secrets:
      TRITONBENCH_SCRIBE_GRAPHQL_ACCESS_TOKEN: ${{ secrets.TRITONBENCH_SCRIBE_GRAPHQL_ACCESS_TOKEN }}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true
